version = 3
final_space = true
console_title_template = '{{ if .Root }}Admin {{ end }}{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    template = '{{ .Path }}'
    style = 'plain'
    foreground = 'lightGreen'
    background = 'transparent'

    [blocks.segments.properties]
      style = 'agnoster_short'
      max_depth = 3
      hide_root_location = true

  [[blocks.segments]]
    type = 'git'
    template = ' {{ regexReplaceAll "^.*/(.+)$" .HEAD "${1}" }}{{ if gt .Working.Unmerged 0 }} !{{ .Working.Unmerged }}{{ end }}{{ if gt (add .Working.Added .Working.Modified .Working.Deleted .Working.Untracked) 0 }} ∗{{ add .Working.Added .Working.Modified .Working.Deleted .Working.Untracked }}{{ end }}{{ if gt (add .Staging.Added .Staging.Modified .Staging.Deleted) 0 }} +{{ add .Staging.Added .Staging.Modified .Staging.Deleted }}{{ end }} {{ .BranchStatus }}'
	style = 'plain'
    foreground = 'cyan'
    background = 'transparent'
    foreground_templates = [
		'{{ if .Merge }}lightMagenta{{ end }}',
		'{{ if .Rebase }}lightMagenta{{ end }}',
		'{{ if .CherryPick }}lightMagenta{{ end }}',
		'{{ if .Revert }}lightMagenta{{ end }}',
		'{{ if .Detached }}lightRed{{ end }}',
		'{{ if gt .Behind 0 }}lightRed{{ end }}',
		'{{ if .Working.Changed }}yellow{{ end }}',
		'{{ if .Staging.Changed }}yellow{{ end }}'
      ]

    [blocks.segments.properties]
	  source = "cli"
      fetch_status = true
	  fetch_push_status = true
      branch_icon = ''
	  commit_icon = ''
	  tag_icon = ''
	  rebase_icon = ''
	  cherry_pick_icon = ''
	  revert_icon = ''
	  merge_icon = ''
	  no_commits_icon = ''

  [[blocks.segments]]
    type = 'executiontime'
    template = ' {{ .FormattedMs }}'
    style = 'plain'
    foreground = 'lightMagenta'

    [blocks.segments.properties]
      style = 'austin'
      threshold = 500

  [[blocks.segments]]
    type = 'exit'
    template = ' {{ .Meaning }}'
    style = 'plain'
    foreground = 'lightRed'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = 'lightMagenta'

    [blocks.segments.properties]
      time_format = '15:04:05'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}lightRed{{end}}",
      "{{if eq .Code 0}}lightGreen{{end}}",
    ]
    background = 'transparent'
    template = '❯ '

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}lightRed{{end}}",
    "{{if eq .Code 0}}lightGreen{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'lightGreen'
  background = 'transparent'
  template = '❯❯ '

[[tooltips]]
  type = "az"
  template = '<cyan>{{ .User.Name }}</> at <green>{{ .Name }}</>'
  style = "plain"
  tips = [ "az", "terraform" ]

  [tooltips.properties]
    source = "cli"
